server:
  port: 8081

spring:
  application:
    name: aadhar-service

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Bastia@9090

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    prefer-ip-address: true           # <== REQUIRED: Use IP instead of hostname
    hostname: localhost              # <== Optional: Forces it to register as localhost
