server:
  port: 8084 # or 8083 for product-service

spring:
  application:
    name: order-service # or product-service

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Bastia@9090

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  tracing:
    sampling:
      probability: 1.0
    propagation: b3 # Explicitly set propagation format to B3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # Standard Zipkin endpoint
  endpoints:
    web:
      exposure:
        include: "*" # Expose all actuator endpoints for debugging

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %5p [${spring.application.name},%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
