server:
  port: 8087

spring:
  application:
    name: payment-resilience

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: dev

resilience4j:
  retry:
    instances:
      paymentService:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - java.lang.RuntimeException

  circuitbreaker:
    instances:
      paymentService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
