server:
  port: 8083

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Bastia@9090

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: product-service

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %5p [${spring.application.name},%X{traceId},%X{spanId}] %logger{36} - %msg%n"
